### PR TITLE
V8 changes: in particular, fully V8 enabled coffeescript asset compiler

### PR DESCRIPTION
**Pull request by ivanstojic**
With these changes, the V8 asset compiler is now fully JS-engine aware, uses the new clj-v8 wrappers, recognizes and reports errors and everything. Note: only the coffeescript asset compiler has been ported over. Some work still left to be done on hamlcoffee and less, along with testing.

### CODE REVIEW

**Comment by ivanstojic** [comment]
Added a commit to close Dieter's issue #10

**Comment by pbiggar** [comment]
Github won't auto merge this. do you need me to merge it manually?

**Comment by ivanstojic** [comment]
Sure, merge manually and then I'll re-fork my own repo direct from edgecase/dieter instead of the long way around.

**Comment by pbiggar** [comment]
I fixed a few merge conflicts, then go:

 $ lein test
Copying 34 files to /Users/pbiggar/work/dotbuild/dieter/dieter-core/lib
Copying 2 files to /Users/pbiggar/work/dotbuild/dieter/dieter-core/lib/dev

Testing dieter.test.asset.coffeescript
Invalid memory access of location 0x0 rip=0x7fff8ef974f0

**Comment by ivanstojic** [comment]
I'm not sure which OS you are on - I currently only have 64bit OS X compiled in the repo up to the latest version. In any case, before lein test, I'd suggest "rm -rf native/; lein deps; lein clean"

**Comment by ivanstojic** [comment]
Expiration now works as it should.

**Comment by ivanstojic** [comment]
Superseded by the new pull request...

**Pull request closed without merging**
