### PR TITLE
Add support for haml-coffee and coffeescript

### PR DESCRIPTION
**Pull request by pbiggar**

### CODE REVIEW

**Comment by pbiggar** [comment]
The "compression enabled" fix doesn't need to be part of this - I'll remove it. What about the rest of it?

**Comment by jxa** [comment]
This is great. I like the pool idea. I was trying to figure out how to lazy-initialize the rhino contexts. 

I'm reviewing this now. For some reason there are 3 failing tests and 2 errors. Once we get those passing we should be good to merge this.

**Comment by pbiggar** [comment]
Great. One failing test is because I broke the less compiler. I'm working on that today.

I pulled out the error checking, and am going to put the `format-error` functions in the js "wrapper" files for simplicity. I think that accounts for two errors.

A problem with the pool is that it's really slow. Like really slow. I'll get that fixed soon too (we're building our website out now, so we'll be working on dieter a bit more - I also need asset precompilation, which I don't think is there yet?)

**Comment by pbiggar** [comment]
FYI: those tests are fixed now.

**Comment by jxa** [comment]
One test still failing:

```
java.lang.RuntimeException: Unsupported escape character: \], compiling:(dieter/test/preprocessors/coffeescript.clj:20)
```

Removing the backslash makes it pass for me.

Merged to master. Tomorrow we'll try it out on our app & if everything looks good I'll cut a new release version. Thanks for your contributions!

**Comment by pbiggar** [comment]
Weird, I needed to add that backslash to make it work, though it didnt make sense to me. Glad it got removed.
Fantastic, thanks for the cool library. And let me know if you have performance issues from the pool.

**Comment by pbiggar** [comment]
This is merged, so closing.

**Pull request closed without merging**
