### PR TITLE
make lein-dieter-precompile work with lein2

### PR DESCRIPTION
**Pull request by pelle**
Just a few small changes needed for it to work

### CODE REVIEW

**Comment by pbiggar** [comment]
Does it still work with lein1?

**Comment by bmabey** [comment]
I tried this patch and I got the following error with lein 2.0.0-preview 10:

```
Exception in thread "main" java.io.FileNotFoundException: Could not locate leiningen/dieter_precompile/runtime__init.class or leiningen/dieter_precompile/runtime.clj on classpath:
```

**Comment by bmabey** [comment]
I found out why the plugin no longer works... with lein2 the plugin is no longer on the CLASSPATH.  Midje ran into the same problem and this is how they solved it: https://github.com/marick/lein-midje/blob/master/src/leiningen/midje.clj#L92-L97

**Comment by si14** [comment]
Any updates with this? I would really like to use Dieter as a plugin, but this issue is a showstopper.

**Comment by pelle** [comment]
Sorry I'm not currently using dieter so I haven't had time to look more into this.

**Comment by pbiggar** [comment]
This might have been fixed by https://github.com/edgecase/dieter/pull/35

**Comment by pbiggar** [comment]
This was definitely fixed in version 0.3.0

**Pull request closed without merging**
